### ISSUE TITLE
Searching OneDrive through SDK returns wrong parent_id

### ISSUE THREAD

**Issue by scpc0609** [liveservices/LiveSDK#22] opened 2014-12-17 15:00 UTC
A replica of the msdn forum issue as it seems that nobody is monitoring there.

I am trying to search onedrive through live sdk.

When I retrieve normally the "Pictures" folder has the following attributes:

id: folder.29cee92602f9e99d.29CEE92602F9E99D!890

parent_id: folder.29cee92602f9e99d

But when I retrieve through search queries, the same "Pictures" folder reveal the following in the search response:

id: folder.29cee92602f9e99d.29CEE92602F9E99D!890

parent_id: folder.29cee92602f9e99d.29CEE92602F9E99D!105

As you can see the parent_id is broken, and as usual when I parse the parent_id and try to use it to retrieve parent object I get "resource not found" exception message. Is this a bug in the search endpoint, or am I missing something? Is there any workaround?

**Comment by peternied** [comment] 2015-01-07 00:51
This is a small bug in how the search data population works, and we aren't taking any changes in that space right now.

**Comment by scpc0609** [comment] 2015-01-07 11:06
Hi, Thanks for your response. This might be "small bug" for you but big for me and my app. I am unable to understand how can a issue with API that returns wrong unique id for an object can be a treated as small bug and closed. Though I understand that the problem might be at the api endpoint and not this live sdk. Can you please open up this issue or post an workaround other than sending another query with the primary object's id to get it's parent id?

**Comment by peternied** [comment] 2015-01-08 06:30
Gotcha.  I have figured out what is wrong in our internal systems, and I've got a fix that will be out when our next major release gets to market.  The problem is that we are exposing an internal data value that represents your root OneDrive folder, but our permission model with the LiveSDK does not let you query that value directly.

As to a workaround.  There is a way to do this, but this is a *terrible* **terrible** hack that should be marked as such in your code and it should be expected that in time this will break.  With that disclaimer, you can perform a little dissection on the resource ids to know if you are using the broken placeholder.

Consider the following ID:
> file.8ae9dbc6c4a4c.8AE9DBC6C4A4C!39598

| Example | Section |  Representation |
|--------|-------------|-------------|
| file| 1 | If the item is a file or a folder|
|.8ae9dbc6c4a4c| 2| The group owner for the item|
|.8AE9DBC6C4A4C| 3| The account owner for the item (For your files the same as the group owner)|
|!39598|4|An internal reference number for items|

You could look at this internal reference number and determine if it is one of the numbers that is generated a bad response, around 105 or lower.  These internal values are based on the internal data structures that are created for user accounts with the OneDrive service.  For some older accounts this number could be very high for other accounts this number could be lower.  

I would recommend that to work around this problem by adding the following to two options your program
1) If you detect a value of 110 or less on the resource id of an items parent, request the just that item information a second time so you get a valid parent's information.
2) Before you perform a search, query the root of the users OneDrive account and use that as a reference list to see if the search item's parent is the OneDrive root which you would use in place of the bugged 'id'.

**Comment by scpc0609** [comment] 2015-01-08 13:09
Thank you so much for looking into this issue. I would assume I get a notification via github when this fix is released. As for the workaround, I am currently already querying the parent id with each search result. But that is not appearing an acceptable UX due to additional lags being imposed when the search results are high in number.

Regarding your second point, can you please advise if the issue exists only for the immediate children of the root folder? If that is the case, I can cache the root children and that would solve my purpose. I won't implement this caching if the issue is widespread (deep down the root folder). Please let me know.

**Comment by peternied** [comment] 2015-01-08 17:43
This will happen on items that are at the root of a users OneDrive or a the root of a Group folder, if your app doesn't interact with group folders then you can just keep your root cache fresh and you should be able to avoid this issue.

We'll keep this issue around, and it will be closed when the service patch is live.

**Comment by peternied** [comment] 2015-02-03 18:07
@scpc0609 This change should be live now, could you give it a try and confirm that this is fixed?

**Comment by scpc0609** [comment] 2015-02-04 13:00
Thanks for the update

**Comment by peternied** [comment] 2015-02-13 21:35
Everything should be out now, please let me know if this issue is resolved.

**Comment by scpc0609** [comment] 2015-02-16 10:37
Hi, Thanks for the update. It appears this issues is fixed and can be closed now.

But intermittently I have seen that search takes a long time with empty pages being returned. This is not something that I have seen in the last few days.Not sure something around this has been fixed as well.

**Comment by peternied** [comment] 2015-02-16 18:58
Glad to hear that scenario is fixed.  If you could capture a fiddler trace or something similar of those bad requests I can take a quick look, just open a new issue.

**Closed as completed by peternied** 2015-02-16 18:58 UTC
